Controllers/EvaluationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PlatziAspCore.Models;

namespace PlatziAspCore.Controllers
{
    public class EvaluationController : Controller
    {
        private readonly SchoolContext context;

        public EvaluationController(SchoolContext context)
        {
            this.context = context;
        }

        // GET: Evaluation
        public async Task<IActionResult> Index()
        {
            var schoolContext = context.Evaluations
                                       .Include(e => e.Student)
                                       .Include(e => e.Subject);
            return View(await schoolContext.ToListAsync());
        }

        // GET: Evaluation/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evaluation = await context.Evaluations
                                          .Include(e => e.Student)
                                          .Include(e => e.Subject)
                                          .FirstOrDefaultAsync(m => m.Id == id);
            if (evaluation == null)
            {
                return NotFound();
            }

            return View(evaluation);
        }

        // GET: Evaluation/Create
        public IActionResult Create()
        {
            ViewData["StudentList"] = new SelectList(context.Students, "Id", "Name");
            ViewData["SubjectList"] = new SelectList(context.Subjects, "Id", "Name");
            return View();
        }

        // POST: Evaluation/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,SubjectId,StudentId,Grade,Id")] Evaluation evaluation)
        {
            if (ModelState.IsValid)
            {
                context.Add(evaluation);
                await context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["StudentList"] = new SelectList(context.Students, "Id", "Name", evaluation.StudentId);
            ViewData["SubjectList"] = new SelectList(context.Subjects, "Id", "Name", evaluation.SubjectId);

            return View(evaluation);
        }

        // GET: Evaluation/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evaluation = await context.Evaluations.FindAsync(id);
            if (evaluation == null)
            {
                return NotFound();
            }
            ViewData["StudentList"] = new SelectList(context.Students, "Id", "Name", evaluation.StudentId);
            ViewData["SubjectList"] = new SelectList(context.Subjects, "Id", "Name", evaluation.SubjectId);
            return View(evaluation);
        }

        // POST: Evaluation/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Name,SubjectId,StudentId,Grade,Id")] Evaluation evaluation)
        {
            if (id != evaluation.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    context.Update(evaluation);
                    await context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EvaluationExists(evaluation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["StudentList"] = new SelectList(context.Students, "Id", "Name", evaluation.StudentId);
            ViewData["SubjectList"] = new SelectList(context.Subjects, "Id", "Name", evaluation.SubjectId);
            return View(evaluation);
        }

        // GET: Evaluation/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evaluation = await context.Evaluations
                                          .Include(e => e.Student)
                                          .Include(e => e.Subject)
                                          .FirstOrDefaultAsync(m => m.Id == id);
            if (evaluation == null)
            {
                return NotFound();
            }

            return View(evaluation);
        }

        // POST: Evaluation/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var evaluation = await context.Evaluations.FindAsync(id);
            context.Evaluations.Remove(evaluation);
            await context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EvaluationExists(string id)
        {
            return context.Evaluations.Any(e => e.Id == id);
        }
    }
}

Controllers/SchoolController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PlatziAspCore.Models;

namespace PlatziAspCore.Controllers
{
    public class SchoolController : Controller
    {
        private readonly SchoolContext context;

        public SchoolController(SchoolContext context)
        {
            this.context = context;
        }

        // GET: School

        public async Task<IActionResult> Index()
        {
            return View(await context.Schools.ToListAsync());
        }

        // GET: School/Details/5
        [Route("School/{schoolId}")]
        [Route("School/Details/{schoolId}")]
        public async Task<IActionResult> Details(string schoolId)
        {
            if (schoolId == null)
            {
                return NotFound();
            }

            var school = await context.Schools
                .FirstOrDefaultAsync(m => m.Id == schoolId);
            if (school == null)
            {
                return NotFound();
            }

            return View(school);
        }

        // GET: Schools/Create
        [Route("School/Create")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Schools/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("School/Create")]
        public async Task<IActionResult> Create(School school)
        {
            if (ModelState.IsValid)
            {
                context.Add(school);
                await context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(school);
        }

        // GET: Schools/Edit/5
        [Route("School/Edit/{schoolId}")]
        public async Task<IActionResult> Edit(string schoolId)
        {
            if (schoolId == null)
            {
                return NotFound();
            }

            var school = await context.Schools.FindAsync(schoolId);
            if (school == null)
            {
                return NotFound();
            }
            return View(school);
        }

        // POST: Schools/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("FoundationYear,Address,Country,City,SchoolType,Id,Name")] School school)
        {
            if (id != school.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    context.Update(school);
                    await context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SchoolExists(school.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(school);
        }

        // GET: Schools/Delete/5
        [Route("School/Delete/{schoolId}")]
        public async Task<IActionResult> Delete(string schoolId)
        {
            if (schoolId == null)
            {
                return NotFound();
            }

            var school = await context.Schools.FirstOrDefaultAsync(m => m.Id == schoolId);
            if (school == null)
            {
                return NotFound();
            }

            return View(school);
        }

        // POST: Schools/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var school = await context.Schools.FindAsync(id);
            context.Schools.Remove(school);
            await context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SchoolExists(string id)
        {
            return context.Schools.Any(e => e.Id == id);
        }
    }
}

Views/Shared/SchoolObjectList.cshtml
@* @model List<BaseSchoolObject> *@

<table class="table table-hover table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">
                @*@Html.DisplayNameFor(model => model.Name)*@
                Name
            </th>
            <th scope="col">
                @*@Html.DisplayNameFor(model => model.DayType)*@
                Id
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.School)
                </th>*@
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var schoolObject in Model)
        {
            <tr>
                <td scope="row">
                    @* @Html.DisplayFor(modelItem => schoolObject.Name)*@
                    @schoolObject.Name
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => schoolObject.DayType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => schoolObject.Address)
                </td>*@
                <td>
                    @*@Html.DisplayFor(modelItem => schoolObject.School.Id)*@
                    @schoolObject.Id
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@schoolObject.Id" class="btn btn-success">Edit</a>
                    <a asp-action="Details" asp-route-id="@schoolObject.Id" class="btn btn-info">Details</a>
                    <a asp-action="Delete" asp-route-id="@schoolObject.Id" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Shared/SchoolObjectSimple.cshtml
@model BaseSchoolObject

<p>
    Name:@Model.Name <br />
    Id : @Model.Id
</p>

Views/Shared/Simple.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- <title>@ViewData["Title"]</title> -->

    <environment include="Development">
         <link rel="stylesheet"
       href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" 
       integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
       crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
       <link rel="stylesheet"
       href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" 
       integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
       crossorigin="anonymous">
     </environment>
</head>
<body>   
    @RenderBody()
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
            crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" 
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" 
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" 
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" 
            crossorigin="anonymous"></script>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PlatziAspCore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">PlatziAspCore</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="School" asp-action="Index">School</a></li>
                    <li><a asp-area="" asp-controller="Course" asp-action="Index">Course</a></li>
                    <li><a asp-area="" asp-controller="Subject" asp-action="Index">Subject</a></li>
                    <li><a asp-area="" asp-controller="Student" asp-action="Index">Student</a></li>
                    <li><a asp-area="" asp-controller="Evaluation" asp-action="Index">Evaluation</a></li>

                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - PlatziAspCore</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>